[build]
  publish = "."

[[context.production.plugins]]
package = "@netlify/plugin-sitemap"
  [context.production.plugins.inputs]
  buildDir = "."

[[redirects]]
from = "/sitemap.xml"
to = "/sitemap.xml"
status = 200

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
